@server=http://localhost:8080
@username=authenticated
@password=


### A_BusinessPartner
# @name A_BusinessPartner_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner
Authorization: Basic {{username}}:{{password}}


### A_BusinessPartner
# @name A_BusinessPartner_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "BusinessPartner": "er-9276689",
  "Customer": "er-9276689",
  "Supplier": "er-9276689",
  "AcademicTitle": "6689",
  "AuthorizationGroup": "6689",
  "BusinessPartnerCategory": "9",
  "BusinessPartnerFullName": "BusinessPartnerFullName-9276689",
  "BusinessPartnerGrouping": "6689",
  "BusinessPartnerName": "BusinessPartnerName-9276689",
  "BusinessPartnerUUID": "9276689f-f142-4f63-8742-7444ada632ce",
  "CorrespondenceLanguage": "89",
  "CreatedByUser": "User-9276689",
  "CreationDate": "2018-10-18",
  "CreationTime": "22:59:53",
  "FirstName": "FirstName-9276689",
  "FormOfAddress": "6689",
  "Industry": "ry-9276689",
  "IsNaturalPerson": "9",
  "Language": "89",
  "LastChangeDate": "2009-08-16",
  "LastChangeTime": "22:59:53",
  "LastChangedByUser": "User-9276689",
  "LastName": "LastName-9276689",
  "LegalForm": "89",
  "OrganizationBPName1": "OrganizationBPName1-9276689",
  "OrganizationBPName2": "OrganizationBPName2-9276689",
  "OrganizationBPName3": "OrganizationBPName3-9276689",
  "OrganizationBPName4": "OrganizationBPName4-9276689",
  "OrganizationFoundationDate": "2006-02-12",
  "OrganizationLiquidationDate": "2023-07-07",
  "SearchTerm1": "SearchTerm1-9276689",
  "SearchTerm2": "SearchTerm2-9276689",
  "BirthDate": "2021-08-20",
  "BusinessPartnerBirthplaceName": "BusinessPartnerBirthplaceName-9276689",
  "BusinessPartnerDeathDate": "2007-12-03",
  "BusinessPartnerIsBlocked": false,
  "BusinessPartnerType": "6689",
  "GroupBusinessPartnerName1": "GroupBusinessPartnerName1-9276689",
  "GroupBusinessPartnerName2": "GroupBusinessPartnerName2-9276689",
  "MiddleName": "MiddleName-9276689",
  "NameCountry": "689",
  "PersonFullName": "PersonFullName-9276689",
  "PersonNumber": "er-9276689",
  "IsMarkedForArchiving": false,
  "BusinessPartnerIDByExtSystem": "DByExtSystem-9276689",
  "TradingPartner": "276689",
  "to_BusinessPartnerAddress": [
    {
      "AddressID": "s-25951488",
      "ValidityStartDate": "2008-11-04T00:00:00.000Z",
      "ValidityEndDate": "2020-10-09T00:00:00.000Z",
      "AuthorizationGroup": "1488",
      "AddressUUID": "25951488-613a-46f8-980e-7b29c50710ef",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951488",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951488",
      "AddressTimeZone": "951488",
      "CareOfName": "CareOfName-25951488",
      "CityCode": "ode-25951488",
      "CityName": "CityName-25951488",
      "CompanyPostalCode": "e-25951488",
      "Country": "488",
      "County": "County-25951488",
      "DeliveryServiceNumber": "r-25951488",
      "DeliveryServiceTypeCode": "1488",
      "District": "District-25951488",
      "FormOfAddress": "1488",
      "FullName": "FullName-25951488",
      "HomeCityName": "HomeCityName-25951488",
      "HouseNumber": "r-25951488",
      "HouseNumberSupplementText": "t-25951488",
      "Language": "88",
      "POBox": "x-25951488",
      "POBoxIsWithoutNumber": true,
      "POBoxPostalCode": "e-25951488",
      "Person": "n-25951488",
      "PostalCode": "e-25951488",
      "Region": "488",
      "StreetName": "StreetName-25951488",
      "StreetPrefixName": "StreetPrefixName-25951488",
      "StreetSuffixName": "StreetSuffixName-25951488",
      "TaxJurisdiction": "iction-25951488",
      "TransportZone": "e-25951488",
      "IsDefaultAddress": true,
      "to_EmailAddress": [
        {
          "Person": "s-29098814",
          "OrdinalNumber": "814",
          "IsDefaultEmailAddress": true,
          "EmailAddress": "EmailAddress-29098814",
          "SearchEmailAddress": "mailAddress-29098814",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
        },
        {
          "Person": "s-29098815",
          "OrdinalNumber": "815",
          "IsDefaultEmailAddress": false,
          "EmailAddress": "EmailAddress-29098815",
          "SearchEmailAddress": "mailAddress-29098815",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098815"
        }
      ],
      "to_PhoneNumber": [
        {
          "Person": "r-28339457",
          "OrdinalNumber": "457",
          "DestinationLocationCountry": "457",
          "Connection": "Connection-28339457",
          "IsDefaultPhoneNumber": false,
          "IsDefaultSmSNumber": false,
          "PhoneNumber": "PhoneNumber-28339457",
          "PhoneNumberType": "7",
          "PhoneExtensionNumber": "r-28339457",
          "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
        },
        {
          "Person": "r-28339458",
          "OrdinalNumber": "458",
          "DestinationLocationCountry": "458",
          "Connection": "Connection-28339458",
          "IsDefaultPhoneNumber": true,
          "IsDefaultSmSNumber": true,
          "PhoneNumber": "PhoneNumber-28339458",
          "PhoneNumberType": "8",
          "PhoneExtensionNumber": "r-28339458",
          "InternationalPhoneNumber": "ernationalPhoneNumber-28339458",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339458"
        }
      ]
    },
    {
      "AddressID": "s-25951489",
      "ValidityStartDate": "2003-09-27T00:00:00.000Z",
      "ValidityEndDate": "2000-10-10T00:00:00.000Z",
      "AuthorizationGroup": "1489",
      "AddressUUID": "25951489-82d0-44b7-8847-1b6253fb2971",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951489",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951489",
      "AddressTimeZone": "951489",
      "CareOfName": "CareOfName-25951489",
      "CityCode": "ode-25951489",
      "CityName": "CityName-25951489",
      "CompanyPostalCode": "e-25951489",
      "Country": "489",
      "County": "County-25951489",
      "DeliveryServiceNumber": "r-25951489",
      "DeliveryServiceTypeCode": "1489",
      "District": "District-25951489",
      "FormOfAddress": "1489",
      "FullName": "FullName-25951489",
      "HomeCityName": "HomeCityName-25951489",
      "HouseNumber": "r-25951489",
      "HouseNumberSupplementText": "t-25951489",
      "Language": "89",
      "POBox": "x-25951489",
      "POBoxIsWithoutNumber": false,
      "POBoxPostalCode": "e-25951489",
      "Person": "n-25951489",
      "PostalCode": "e-25951489",
      "Region": "489",
      "StreetName": "StreetName-25951489",
      "StreetPrefixName": "StreetPrefixName-25951489",
      "StreetSuffixName": "StreetSuffixName-25951489",
      "TaxJurisdiction": "iction-25951489",
      "TransportZone": "e-25951489",
      "IsDefaultAddress": false,
      "to_EmailAddress": [
        {
          "Person": "ess-305809",
          "OrdinalNumber": "809",
          "IsDefaultEmailAddress": false,
          "EmailAddress": "EmailAddress-305809",
          "SearchEmailAddress": "hEmailAddress-305809",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-305809"
        },
        {
          "Person": "ess-305810",
          "OrdinalNumber": "810",
          "IsDefaultEmailAddress": true,
          "EmailAddress": "EmailAddress-305810",
          "SearchEmailAddress": "hEmailAddress-305810",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-305810"
        }
      ],
      "to_PhoneNumber": [
        {
          "Person": "er-3633142",
          "OrdinalNumber": "142",
          "DestinationLocationCountry": "142",
          "Connection": "Connection-3633142",
          "IsDefaultPhoneNumber": true,
          "IsDefaultSmSNumber": true,
          "PhoneNumber": "PhoneNumber-3633142",
          "PhoneNumberType": "2",
          "PhoneExtensionNumber": "er-3633142",
          "InternationalPhoneNumber": "ternationalPhoneNumber-3633142",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-3633142"
        },
        {
          "Person": "er-3633143",
          "OrdinalNumber": "143",
          "DestinationLocationCountry": "143",
          "Connection": "Connection-3633143",
          "IsDefaultPhoneNumber": false,
          "IsDefaultSmSNumber": false,
          "PhoneNumber": "PhoneNumber-3633143",
          "PhoneNumberType": "3",
          "PhoneExtensionNumber": "er-3633143",
          "InternationalPhoneNumber": "ternationalPhoneNumber-3633143",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-3633143"
        }
      ]
    }
  ],
  "to_Customer": {
    "Customer": "r-20665672"
  },
  "to_Supplier": {
    "Supplier": "r-24747136"
  }
}


### A_BusinessPartner
# @name A_BusinessPartner_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner/er-9276689
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "BusinessPartner": "er-9276689",
  "Customer": "er-9276689",
  "Supplier": "er-9276689",
  "AcademicTitle": "6689",
  "AuthorizationGroup": "6689",
  "BusinessPartnerCategory": "9",
  "BusinessPartnerFullName": "BusinessPartnerFullName-9276689",
  "BusinessPartnerGrouping": "6689",
  "BusinessPartnerName": "BusinessPartnerName-9276689",
  "BusinessPartnerUUID": "9276689f-f142-4f63-8742-7444ada632ce",
  "CorrespondenceLanguage": "89",
  "CreatedByUser": "User-9276689",
  "CreationDate": "2018-10-18",
  "CreationTime": "22:59:53",
  "FirstName": "FirstName-9276689",
  "FormOfAddress": "6689",
  "Industry": "ry-9276689",
  "IsNaturalPerson": "9",
  "Language": "89",
  "LastChangeDate": "2009-08-16",
  "LastChangeTime": "22:59:53",
  "LastChangedByUser": "User-9276689",
  "LastName": "LastName-9276689",
  "LegalForm": "89",
  "OrganizationBPName1": "OrganizationBPName1-9276689",
  "OrganizationBPName2": "OrganizationBPName2-9276689",
  "OrganizationBPName3": "OrganizationBPName3-9276689",
  "OrganizationBPName4": "OrganizationBPName4-9276689",
  "OrganizationFoundationDate": "2006-02-12",
  "OrganizationLiquidationDate": "2023-07-07",
  "SearchTerm1": "SearchTerm1-9276689",
  "SearchTerm2": "SearchTerm2-9276689",
  "BirthDate": "2021-08-20",
  "BusinessPartnerBirthplaceName": "BusinessPartnerBirthplaceName-9276689",
  "BusinessPartnerDeathDate": "2007-12-03",
  "BusinessPartnerIsBlocked": false,
  "BusinessPartnerType": "6689",
  "GroupBusinessPartnerName1": "GroupBusinessPartnerName1-9276689",
  "GroupBusinessPartnerName2": "GroupBusinessPartnerName2-9276689",
  "MiddleName": "MiddleName-9276689",
  "NameCountry": "689",
  "PersonFullName": "PersonFullName-9276689",
  "PersonNumber": "er-9276689",
  "IsMarkedForArchiving": false,
  "BusinessPartnerIDByExtSystem": "DByExtSystem-9276689",
  "TradingPartner": "276689",
  "to_BusinessPartnerAddress": [
    {
      "AddressID": "s-25951488",
      "ValidityStartDate": "2008-11-04T00:00:00.000Z",
      "ValidityEndDate": "2020-10-09T00:00:00.000Z",
      "AuthorizationGroup": "1488",
      "AddressUUID": "25951488-613a-46f8-980e-7b29c50710ef",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951488",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951488",
      "AddressTimeZone": "951488",
      "CareOfName": "CareOfName-25951488",
      "CityCode": "ode-25951488",
      "CityName": "CityName-25951488",
      "CompanyPostalCode": "e-25951488",
      "Country": "488",
      "County": "County-25951488",
      "DeliveryServiceNumber": "r-25951488",
      "DeliveryServiceTypeCode": "1488",
      "District": "District-25951488",
      "FormOfAddress": "1488",
      "FullName": "FullName-25951488",
      "HomeCityName": "HomeCityName-25951488",
      "HouseNumber": "r-25951488",
      "HouseNumberSupplementText": "t-25951488",
      "Language": "88",
      "POBox": "x-25951488",
      "POBoxIsWithoutNumber": true,
      "POBoxPostalCode": "e-25951488",
      "Person": "n-25951488",
      "PostalCode": "e-25951488",
      "Region": "488",
      "StreetName": "StreetName-25951488",
      "StreetPrefixName": "StreetPrefixName-25951488",
      "StreetSuffixName": "StreetSuffixName-25951488",
      "TaxJurisdiction": "iction-25951488",
      "TransportZone": "e-25951488",
      "IsDefaultAddress": true,
      "to_EmailAddress": [
        {
          "Person": "s-29098814",
          "OrdinalNumber": "814",
          "IsDefaultEmailAddress": true,
          "EmailAddress": "EmailAddress-29098814",
          "SearchEmailAddress": "mailAddress-29098814",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
        },
        {
          "Person": "s-29098815",
          "OrdinalNumber": "815",
          "IsDefaultEmailAddress": false,
          "EmailAddress": "EmailAddress-29098815",
          "SearchEmailAddress": "mailAddress-29098815",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098815"
        }
      ],
      "to_PhoneNumber": [
        {
          "Person": "r-28339457",
          "OrdinalNumber": "457",
          "DestinationLocationCountry": "457",
          "Connection": "Connection-28339457",
          "IsDefaultPhoneNumber": false,
          "IsDefaultSmSNumber": false,
          "PhoneNumber": "PhoneNumber-28339457",
          "PhoneNumberType": "7",
          "PhoneExtensionNumber": "r-28339457",
          "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
        },
        {
          "Person": "r-28339458",
          "OrdinalNumber": "458",
          "DestinationLocationCountry": "458",
          "Connection": "Connection-28339458",
          "IsDefaultPhoneNumber": true,
          "IsDefaultSmSNumber": true,
          "PhoneNumber": "PhoneNumber-28339458",
          "PhoneNumberType": "8",
          "PhoneExtensionNumber": "r-28339458",
          "InternationalPhoneNumber": "ernationalPhoneNumber-28339458",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339458"
        }
      ]
    },
    {
      "AddressID": "s-25951489",
      "ValidityStartDate": "2003-09-27T00:00:00.000Z",
      "ValidityEndDate": "2000-10-10T00:00:00.000Z",
      "AuthorizationGroup": "1489",
      "AddressUUID": "25951489-82d0-44b7-8847-1b6253fb2971",
      "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951489",
      "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951489",
      "AddressTimeZone": "951489",
      "CareOfName": "CareOfName-25951489",
      "CityCode": "ode-25951489",
      "CityName": "CityName-25951489",
      "CompanyPostalCode": "e-25951489",
      "Country": "489",
      "County": "County-25951489",
      "DeliveryServiceNumber": "r-25951489",
      "DeliveryServiceTypeCode": "1489",
      "District": "District-25951489",
      "FormOfAddress": "1489",
      "FullName": "FullName-25951489",
      "HomeCityName": "HomeCityName-25951489",
      "HouseNumber": "r-25951489",
      "HouseNumberSupplementText": "t-25951489",
      "Language": "89",
      "POBox": "x-25951489",
      "POBoxIsWithoutNumber": false,
      "POBoxPostalCode": "e-25951489",
      "Person": "n-25951489",
      "PostalCode": "e-25951489",
      "Region": "489",
      "StreetName": "StreetName-25951489",
      "StreetPrefixName": "StreetPrefixName-25951489",
      "StreetSuffixName": "StreetSuffixName-25951489",
      "TaxJurisdiction": "iction-25951489",
      "TransportZone": "e-25951489",
      "IsDefaultAddress": false,
      "to_EmailAddress": [
        {
          "Person": "ess-305809",
          "OrdinalNumber": "809",
          "IsDefaultEmailAddress": false,
          "EmailAddress": "EmailAddress-305809",
          "SearchEmailAddress": "hEmailAddress-305809",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-305809"
        },
        {
          "Person": "ess-305810",
          "OrdinalNumber": "810",
          "IsDefaultEmailAddress": true,
          "EmailAddress": "EmailAddress-305810",
          "SearchEmailAddress": "hEmailAddress-305810",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-305810"
        }
      ],
      "to_PhoneNumber": [
        {
          "Person": "er-3633142",
          "OrdinalNumber": "142",
          "DestinationLocationCountry": "142",
          "Connection": "Connection-3633142",
          "IsDefaultPhoneNumber": true,
          "IsDefaultSmSNumber": true,
          "PhoneNumber": "PhoneNumber-3633142",
          "PhoneNumberType": "2",
          "PhoneExtensionNumber": "er-3633142",
          "InternationalPhoneNumber": "ternationalPhoneNumber-3633142",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-3633142"
        },
        {
          "Person": "er-3633143",
          "OrdinalNumber": "143",
          "DestinationLocationCountry": "143",
          "Connection": "Connection-3633143",
          "IsDefaultPhoneNumber": false,
          "IsDefaultSmSNumber": false,
          "PhoneNumber": "PhoneNumber-3633143",
          "PhoneNumberType": "3",
          "PhoneExtensionNumber": "er-3633143",
          "InternationalPhoneNumber": "ternationalPhoneNumber-3633143",
          "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-3633143"
        }
      ]
    }
  ],
  "to_Customer": {
    "Customer": "r-20665672"
  },
  "to_Supplier": {
    "Supplier": "r-24747136"
  }
}


### A_BusinessPartner
# @name A_BusinessPartner_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner/er-9276689
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_BusinessPartnerAddress
# @name A_BusinessPartnerAddress_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartnerAddress
Authorization: Basic {{username}}:{{password}}


### A_BusinessPartnerAddress
# @name A_BusinessPartnerAddress_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartnerAddress
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "AddressID": "s-25951488",
  "ValidityStartDate": "2008-11-04T00:00:00.000Z",
  "ValidityEndDate": "2020-10-09T00:00:00.000Z",
  "AuthorizationGroup": "1488",
  "AddressUUID": "25951488-613a-46f8-980e-7b29c50710ef",
  "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951488",
  "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951488",
  "AddressTimeZone": "951488",
  "CareOfName": "CareOfName-25951488",
  "CityCode": "ode-25951488",
  "CityName": "CityName-25951488",
  "CompanyPostalCode": "e-25951488",
  "Country": "488",
  "County": "County-25951488",
  "DeliveryServiceNumber": "r-25951488",
  "DeliveryServiceTypeCode": "1488",
  "District": "District-25951488",
  "FormOfAddress": "1488",
  "FullName": "FullName-25951488",
  "HomeCityName": "HomeCityName-25951488",
  "HouseNumber": "r-25951488",
  "HouseNumberSupplementText": "t-25951488",
  "Language": "88",
  "POBox": "x-25951488",
  "POBoxIsWithoutNumber": true,
  "POBoxPostalCode": "e-25951488",
  "Person": "n-25951488",
  "PostalCode": "e-25951488",
  "Region": "488",
  "StreetName": "StreetName-25951488",
  "StreetPrefixName": "StreetPrefixName-25951488",
  "StreetSuffixName": "StreetSuffixName-25951488",
  "TaxJurisdiction": "iction-25951488",
  "TransportZone": "e-25951488",
  "IsDefaultAddress": true,
  "to_EmailAddress": [
    {
      "Person": "s-29098814",
      "OrdinalNumber": "814",
      "IsDefaultEmailAddress": true,
      "EmailAddress": "EmailAddress-29098814",
      "SearchEmailAddress": "mailAddress-29098814",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
    },
    {
      "Person": "s-29098815",
      "OrdinalNumber": "815",
      "IsDefaultEmailAddress": false,
      "EmailAddress": "EmailAddress-29098815",
      "SearchEmailAddress": "mailAddress-29098815",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098815"
    }
  ],
  "to_PhoneNumber": [
    {
      "Person": "r-28339457",
      "OrdinalNumber": "457",
      "DestinationLocationCountry": "457",
      "Connection": "Connection-28339457",
      "IsDefaultPhoneNumber": false,
      "IsDefaultSmSNumber": false,
      "PhoneNumber": "PhoneNumber-28339457",
      "PhoneNumberType": "7",
      "PhoneExtensionNumber": "r-28339457",
      "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
    },
    {
      "Person": "r-28339458",
      "OrdinalNumber": "458",
      "DestinationLocationCountry": "458",
      "Connection": "Connection-28339458",
      "IsDefaultPhoneNumber": true,
      "IsDefaultSmSNumber": true,
      "PhoneNumber": "PhoneNumber-28339458",
      "PhoneNumberType": "8",
      "PhoneExtensionNumber": "r-28339458",
      "InternationalPhoneNumber": "ernationalPhoneNumber-28339458",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339458"
    }
  ]
}


### A_BusinessPartnerAddress
# @name A_BusinessPartnerAddress_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartnerAddress(BusinessPartner='er-9276689',AddressID='s-25951488')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "AddressID": "s-25951488",
  "ValidityStartDate": "2008-11-04T00:00:00.000Z",
  "ValidityEndDate": "2020-10-09T00:00:00.000Z",
  "AuthorizationGroup": "1488",
  "AddressUUID": "25951488-613a-46f8-980e-7b29c50710ef",
  "AdditionalStreetPrefixName": "AdditionalStreetPrefixName-25951488",
  "AdditionalStreetSuffixName": "AdditionalStreetSuffixName-25951488",
  "AddressTimeZone": "951488",
  "CareOfName": "CareOfName-25951488",
  "CityCode": "ode-25951488",
  "CityName": "CityName-25951488",
  "CompanyPostalCode": "e-25951488",
  "Country": "488",
  "County": "County-25951488",
  "DeliveryServiceNumber": "r-25951488",
  "DeliveryServiceTypeCode": "1488",
  "District": "District-25951488",
  "FormOfAddress": "1488",
  "FullName": "FullName-25951488",
  "HomeCityName": "HomeCityName-25951488",
  "HouseNumber": "r-25951488",
  "HouseNumberSupplementText": "t-25951488",
  "Language": "88",
  "POBox": "x-25951488",
  "POBoxIsWithoutNumber": true,
  "POBoxPostalCode": "e-25951488",
  "Person": "n-25951488",
  "PostalCode": "e-25951488",
  "Region": "488",
  "StreetName": "StreetName-25951488",
  "StreetPrefixName": "StreetPrefixName-25951488",
  "StreetSuffixName": "StreetSuffixName-25951488",
  "TaxJurisdiction": "iction-25951488",
  "TransportZone": "e-25951488",
  "IsDefaultAddress": true,
  "to_EmailAddress": [
    {
      "Person": "s-29098814",
      "OrdinalNumber": "814",
      "IsDefaultEmailAddress": true,
      "EmailAddress": "EmailAddress-29098814",
      "SearchEmailAddress": "mailAddress-29098814",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
    },
    {
      "Person": "s-29098815",
      "OrdinalNumber": "815",
      "IsDefaultEmailAddress": false,
      "EmailAddress": "EmailAddress-29098815",
      "SearchEmailAddress": "mailAddress-29098815",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098815"
    }
  ],
  "to_PhoneNumber": [
    {
      "Person": "r-28339457",
      "OrdinalNumber": "457",
      "DestinationLocationCountry": "457",
      "Connection": "Connection-28339457",
      "IsDefaultPhoneNumber": false,
      "IsDefaultSmSNumber": false,
      "PhoneNumber": "PhoneNumber-28339457",
      "PhoneNumberType": "7",
      "PhoneExtensionNumber": "r-28339457",
      "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
    },
    {
      "Person": "r-28339458",
      "OrdinalNumber": "458",
      "DestinationLocationCountry": "458",
      "Connection": "Connection-28339458",
      "IsDefaultPhoneNumber": true,
      "IsDefaultSmSNumber": true,
      "PhoneNumber": "PhoneNumber-28339458",
      "PhoneNumberType": "8",
      "PhoneExtensionNumber": "r-28339458",
      "InternationalPhoneNumber": "ernationalPhoneNumber-28339458",
      "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339458"
    }
  ]
}


### A_BusinessPartnerAddress
# @name A_BusinessPartnerAddress_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartnerAddress(BusinessPartner='er-9276689',AddressID='s-25951488')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_AddressEmailAddress
# @name A_AddressEmailAddress_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressEmailAddress
Authorization: Basic {{username}}:{{password}}


### A_AddressEmailAddress
# @name A_AddressEmailAddress_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressEmailAddress
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": "s-29098814",
  "OrdinalNumber": "814",
  "IsDefaultEmailAddress": true,
  "EmailAddress": "EmailAddress-29098814",
  "SearchEmailAddress": "mailAddress-29098814",
  "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
}


### A_AddressEmailAddress
# @name A_AddressEmailAddress_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressEmailAddress(AddressID='s-25951488',Person='s-29098814',OrdinalNumber='814')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": "s-29098814",
  "OrdinalNumber": "814",
  "IsDefaultEmailAddress": true,
  "EmailAddress": "EmailAddress-29098814",
  "SearchEmailAddress": "mailAddress-29098814",
  "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-29098814"
}


### A_AddressEmailAddress
# @name A_AddressEmailAddress_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressEmailAddress(AddressID='s-25951488',Person='s-29098814',OrdinalNumber='814')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_AddressPhoneNumber
# @name A_AddressPhoneNumber_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressPhoneNumber
Authorization: Basic {{username}}:{{password}}


### A_AddressPhoneNumber
# @name A_AddressPhoneNumber_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressPhoneNumber
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": "r-28339457",
  "OrdinalNumber": "457",
  "DestinationLocationCountry": "457",
  "Connection": "Connection-28339457",
  "IsDefaultPhoneNumber": false,
  "IsDefaultSmSNumber": false,
  "PhoneNumber": "PhoneNumber-28339457",
  "PhoneNumberType": "7",
  "PhoneExtensionNumber": "r-28339457",
  "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
  "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
}


### A_AddressPhoneNumber
# @name A_AddressPhoneNumber_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressPhoneNumber(AddressID='s-25951488',Person='r-28339457',OrdinalNumber='457')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Person": "r-28339457",
  "OrdinalNumber": "457",
  "DestinationLocationCountry": "457",
  "Connection": "Connection-28339457",
  "IsDefaultPhoneNumber": false,
  "IsDefaultSmSNumber": false,
  "PhoneNumber": "PhoneNumber-28339457",
  "PhoneNumberType": "7",
  "PhoneExtensionNumber": "r-28339457",
  "InternationalPhoneNumber": "ernationalPhoneNumber-28339457",
  "AddressCommunicationRemarkText": "AddressCommunicationRemarkText-28339457"
}


### A_AddressPhoneNumber
# @name A_AddressPhoneNumber_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_AddressPhoneNumber(AddressID='s-25951488',Person='r-28339457',OrdinalNumber='457')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_Customer
# @name A_Customer_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Customer
Authorization: Basic {{username}}:{{password}}


### A_Customer
# @name A_Customer_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Customer
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Customer": "r-20665672",
  "AuthorizationGroup": "5672",
  "BillingIsBlockedForCustomer": "72",
  "CreatedByUser": "ser-20665672",
  "CreationDate": "2017-01-17",
  "CustomerAccountGroup": "5672",
  "CustomerClassification": "72",
  "CustomerFullName": "CustomerFullName-20665672",
  "CustomerName": "CustomerName-20665672",
  "DeliveryIsBlocked": "72",
  "FreeDefinedAttribute01": "72",
  "NFPartnerIsNaturalPerson": "2",
  "OrderIsBlockedForCustomer": "72",
  "PostingIsBlocked": true,
  "Supplier": "r-20665672",
  "CustomerCorporateGroup": "p-20665672",
  "FiscalAddress": "s-20665672",
  "Industry": "5672",
  "IndustryCode1": "1-20665672",
  "InternationalLocationNumber1": "0665672",
  "InternationalLocationNumber2": "65672",
  "IsMarkedForDeletion": true,
  "to_CustomerSalesArea": [
    {
      "SalesOrganization": "0917",
      "DistributionChannel": "17",
      "Division": "17",
      "AccountByCustomer": "omer-4280917",
      "AuthorizationGroup": "0917",
      "BillingIsBlockedForCustomer": "17",
      "CompleteDeliveryIsDefined": false,
      "CreditControlArea": "0917",
      "Currency": "80917",
      "CustomerABCClassification": "17",
      "CustomerAccountAssignmentGroup": "17",
      "CustomerGroup": "17",
      "CustomerPaymentTerms": "0917",
      "CustomerPriceGroup": "17",
      "CustomerPricingProcedure": "17",
      "DeliveryIsBlockedForCustomer": "17",
      "IncotermsClassification": "917",
      "IncotermsTransferLocation": "ermsTransferLocation-4280917",
      "IncotermsLocation1": "IncotermsLocation1-4280917",
      "IncotermsLocation2": "IncotermsLocation2-4280917",
      "IncotermsVersion": "0917",
      "ItemOrderProbabilityInPercent": "917",
      "ManualInvoiceMaintIsRelevant": false,
      "MaxNmbrOfPartialDelivery": 2,
      "OrderCombinationIsAllowed": false,
      "OrderIsBlockedForCustomer": "17",
      "OverdelivTolrtdLmtRatioInPct": 53.8,
      "PartialDeliveryIsAllowed": "7",
      "PriceListType": "17",
      "ProductTaxClassification1": "7",
      "SalesGroup": "917",
      "SalesItemProposal": "al-4280917",
      "SalesOffice": "0917",
      "ShippingCondition": "17",
      "SlsDocIsRlvtForProofOfDlvry": false,
      "SlsUnlmtdOvrdelivIsAllwd": false,
      "SupplyingPlant": "0917",
      "SalesDistrict": "280917",
      "UnderdelivTolrtdLmtRatioInPct": 35.5,
      "InvoiceDate": "17"
    },
    {
      "SalesOrganization": "0918",
      "DistributionChannel": "18",
      "Division": "18",
      "AccountByCustomer": "omer-4280918",
      "AuthorizationGroup": "0918",
      "BillingIsBlockedForCustomer": "18",
      "CompleteDeliveryIsDefined": true,
      "CreditControlArea": "0918",
      "Currency": "80918",
      "CustomerABCClassification": "18",
      "CustomerAccountAssignmentGroup": "18",
      "CustomerGroup": "18",
      "CustomerPaymentTerms": "0918",
      "CustomerPriceGroup": "18",
      "CustomerPricingProcedure": "18",
      "DeliveryIsBlockedForCustomer": "18",
      "IncotermsClassification": "918",
      "IncotermsTransferLocation": "ermsTransferLocation-4280918",
      "IncotermsLocation1": "IncotermsLocation1-4280918",
      "IncotermsLocation2": "IncotermsLocation2-4280918",
      "IncotermsVersion": "0918",
      "ItemOrderProbabilityInPercent": "918",
      "ManualInvoiceMaintIsRelevant": true,
      "MaxNmbrOfPartialDelivery": 0,
      "OrderCombinationIsAllowed": true,
      "OrderIsBlockedForCustomer": "18",
      "OverdelivTolrtdLmtRatioInPct": 73.8,
      "PartialDeliveryIsAllowed": "8",
      "PriceListType": "18",
      "ProductTaxClassification1": "8",
      "SalesGroup": "918",
      "SalesItemProposal": "al-4280918",
      "SalesOffice": "0918",
      "ShippingCondition": "18",
      "SlsDocIsRlvtForProofOfDlvry": true,
      "SlsUnlmtdOvrdelivIsAllwd": true,
      "SupplyingPlant": "0918",
      "SalesDistrict": "280918",
      "UnderdelivTolrtdLmtRatioInPct": 25,
      "InvoiceDate": "18"
    }
  ]
}


### A_Customer
# @name A_Customer_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Customer/r-20665672
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Customer": "r-20665672",
  "AuthorizationGroup": "5672",
  "BillingIsBlockedForCustomer": "72",
  "CreatedByUser": "ser-20665672",
  "CreationDate": "2017-01-17",
  "CustomerAccountGroup": "5672",
  "CustomerClassification": "72",
  "CustomerFullName": "CustomerFullName-20665672",
  "CustomerName": "CustomerName-20665672",
  "DeliveryIsBlocked": "72",
  "FreeDefinedAttribute01": "72",
  "NFPartnerIsNaturalPerson": "2",
  "OrderIsBlockedForCustomer": "72",
  "PostingIsBlocked": true,
  "Supplier": "r-20665672",
  "CustomerCorporateGroup": "p-20665672",
  "FiscalAddress": "s-20665672",
  "Industry": "5672",
  "IndustryCode1": "1-20665672",
  "InternationalLocationNumber1": "0665672",
  "InternationalLocationNumber2": "65672",
  "IsMarkedForDeletion": true,
  "to_CustomerSalesArea": [
    {
      "SalesOrganization": "0917",
      "DistributionChannel": "17",
      "Division": "17",
      "AccountByCustomer": "omer-4280917",
      "AuthorizationGroup": "0917",
      "BillingIsBlockedForCustomer": "17",
      "CompleteDeliveryIsDefined": false,
      "CreditControlArea": "0917",
      "Currency": "80917",
      "CustomerABCClassification": "17",
      "CustomerAccountAssignmentGroup": "17",
      "CustomerGroup": "17",
      "CustomerPaymentTerms": "0917",
      "CustomerPriceGroup": "17",
      "CustomerPricingProcedure": "17",
      "DeliveryIsBlockedForCustomer": "17",
      "IncotermsClassification": "917",
      "IncotermsTransferLocation": "ermsTransferLocation-4280917",
      "IncotermsLocation1": "IncotermsLocation1-4280917",
      "IncotermsLocation2": "IncotermsLocation2-4280917",
      "IncotermsVersion": "0917",
      "ItemOrderProbabilityInPercent": "917",
      "ManualInvoiceMaintIsRelevant": false,
      "MaxNmbrOfPartialDelivery": 2,
      "OrderCombinationIsAllowed": false,
      "OrderIsBlockedForCustomer": "17",
      "OverdelivTolrtdLmtRatioInPct": 53.8,
      "PartialDeliveryIsAllowed": "7",
      "PriceListType": "17",
      "ProductTaxClassification1": "7",
      "SalesGroup": "917",
      "SalesItemProposal": "al-4280917",
      "SalesOffice": "0917",
      "ShippingCondition": "17",
      "SlsDocIsRlvtForProofOfDlvry": false,
      "SlsUnlmtdOvrdelivIsAllwd": false,
      "SupplyingPlant": "0917",
      "SalesDistrict": "280917",
      "UnderdelivTolrtdLmtRatioInPct": 35.5,
      "InvoiceDate": "17"
    },
    {
      "SalesOrganization": "0918",
      "DistributionChannel": "18",
      "Division": "18",
      "AccountByCustomer": "omer-4280918",
      "AuthorizationGroup": "0918",
      "BillingIsBlockedForCustomer": "18",
      "CompleteDeliveryIsDefined": true,
      "CreditControlArea": "0918",
      "Currency": "80918",
      "CustomerABCClassification": "18",
      "CustomerAccountAssignmentGroup": "18",
      "CustomerGroup": "18",
      "CustomerPaymentTerms": "0918",
      "CustomerPriceGroup": "18",
      "CustomerPricingProcedure": "18",
      "DeliveryIsBlockedForCustomer": "18",
      "IncotermsClassification": "918",
      "IncotermsTransferLocation": "ermsTransferLocation-4280918",
      "IncotermsLocation1": "IncotermsLocation1-4280918",
      "IncotermsLocation2": "IncotermsLocation2-4280918",
      "IncotermsVersion": "0918",
      "ItemOrderProbabilityInPercent": "918",
      "ManualInvoiceMaintIsRelevant": true,
      "MaxNmbrOfPartialDelivery": 0,
      "OrderCombinationIsAllowed": true,
      "OrderIsBlockedForCustomer": "18",
      "OverdelivTolrtdLmtRatioInPct": 73.8,
      "PartialDeliveryIsAllowed": "8",
      "PriceListType": "18",
      "ProductTaxClassification1": "8",
      "SalesGroup": "918",
      "SalesItemProposal": "al-4280918",
      "SalesOffice": "0918",
      "ShippingCondition": "18",
      "SlsDocIsRlvtForProofOfDlvry": true,
      "SlsUnlmtdOvrdelivIsAllwd": true,
      "SupplyingPlant": "0918",
      "SalesDistrict": "280918",
      "UnderdelivTolrtdLmtRatioInPct": 25,
      "InvoiceDate": "18"
    }
  ]
}


### A_Customer
# @name A_Customer_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Customer/r-20665672
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_CustomerSalesArea
# @name A_CustomerSalesArea_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesArea
Authorization: Basic {{username}}:{{password}}


### A_CustomerSalesArea
# @name A_CustomerSalesArea_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesArea
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesOrganization": "0917",
  "DistributionChannel": "17",
  "Division": "17",
  "AccountByCustomer": "omer-4280917",
  "AuthorizationGroup": "0917",
  "BillingIsBlockedForCustomer": "17",
  "CompleteDeliveryIsDefined": false,
  "CreditControlArea": "0917",
  "Currency": "80917",
  "CustomerABCClassification": "17",
  "CustomerAccountAssignmentGroup": "17",
  "CustomerGroup": "17",
  "CustomerPaymentTerms": "0917",
  "CustomerPriceGroup": "17",
  "CustomerPricingProcedure": "17",
  "DeliveryIsBlockedForCustomer": "17",
  "IncotermsClassification": "917",
  "IncotermsTransferLocation": "ermsTransferLocation-4280917",
  "IncotermsLocation1": "IncotermsLocation1-4280917",
  "IncotermsLocation2": "IncotermsLocation2-4280917",
  "IncotermsVersion": "0917",
  "ItemOrderProbabilityInPercent": "917",
  "ManualInvoiceMaintIsRelevant": false,
  "MaxNmbrOfPartialDelivery": 2,
  "OrderCombinationIsAllowed": false,
  "OrderIsBlockedForCustomer": "17",
  "OverdelivTolrtdLmtRatioInPct": 53.8,
  "PartialDeliveryIsAllowed": "7",
  "PriceListType": "17",
  "ProductTaxClassification1": "7",
  "SalesGroup": "917",
  "SalesItemProposal": "al-4280917",
  "SalesOffice": "0917",
  "ShippingCondition": "17",
  "SlsDocIsRlvtForProofOfDlvry": false,
  "SlsUnlmtdOvrdelivIsAllwd": false,
  "SupplyingPlant": "0917",
  "SalesDistrict": "280917",
  "UnderdelivTolrtdLmtRatioInPct": 35.5,
  "InvoiceDate": "17"
}


### A_CustomerSalesArea
# @name A_CustomerSalesArea_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesArea(Customer='r-20665672',SalesOrganization='0917',DistributionChannel='17',Division='17')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesOrganization": "0917",
  "DistributionChannel": "17",
  "Division": "17",
  "AccountByCustomer": "omer-4280917",
  "AuthorizationGroup": "0917",
  "BillingIsBlockedForCustomer": "17",
  "CompleteDeliveryIsDefined": false,
  "CreditControlArea": "0917",
  "Currency": "80917",
  "CustomerABCClassification": "17",
  "CustomerAccountAssignmentGroup": "17",
  "CustomerGroup": "17",
  "CustomerPaymentTerms": "0917",
  "CustomerPriceGroup": "17",
  "CustomerPricingProcedure": "17",
  "DeliveryIsBlockedForCustomer": "17",
  "IncotermsClassification": "917",
  "IncotermsTransferLocation": "ermsTransferLocation-4280917",
  "IncotermsLocation1": "IncotermsLocation1-4280917",
  "IncotermsLocation2": "IncotermsLocation2-4280917",
  "IncotermsVersion": "0917",
  "ItemOrderProbabilityInPercent": "917",
  "ManualInvoiceMaintIsRelevant": false,
  "MaxNmbrOfPartialDelivery": 2,
  "OrderCombinationIsAllowed": false,
  "OrderIsBlockedForCustomer": "17",
  "OverdelivTolrtdLmtRatioInPct": 53.8,
  "PartialDeliveryIsAllowed": "7",
  "PriceListType": "17",
  "ProductTaxClassification1": "7",
  "SalesGroup": "917",
  "SalesItemProposal": "al-4280917",
  "SalesOffice": "0917",
  "ShippingCondition": "17",
  "SlsDocIsRlvtForProofOfDlvry": false,
  "SlsUnlmtdOvrdelivIsAllwd": false,
  "SupplyingPlant": "0917",
  "SalesDistrict": "280917",
  "UnderdelivTolrtdLmtRatioInPct": 35.5,
  "InvoiceDate": "17"
}


### A_CustomerSalesArea
# @name A_CustomerSalesArea_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesArea(Customer='r-20665672',SalesOrganization='0917',DistributionChannel='17',Division='17')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### A_Supplier
# @name A_Supplier_GET
GET {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Supplier
Authorization: Basic {{username}}:{{password}}


### A_Supplier
# @name A_Supplier_POST
POST {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Supplier
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Supplier": "r-24747136",
  "AuthorizationGroup": "7136",
  "CreatedByUser": "ser-24747136",
  "CreationDate": "2010-04-10",
  "Customer": "r-24747136",
  "IsMarkedForDeletion": true,
  "IsNaturalPerson": "6",
  "PaymentIsBlockedForSupplier": true,
  "PostingIsBlocked": true,
  "PurchasingIsBlocked": true,
  "SupplierAccountGroup": "7136",
  "SupplierFullName": "SupplierFullName-24747136",
  "SupplierName": "SupplierName-24747136",
  "VATRegistration": "egistration-24747136",
  "BirthDate": "2007-06-24",
  "ConcatenatedInternationalLocNo": "LocNo-24747136",
  "DeletionIndicator": true,
  "FiscalAddress": "s-24747136",
  "Industry": "7136",
  "InternationalLocationNumber1": "4747136",
  "InternationalLocationNumber2": "47136",
  "IsNaturalPerson2": "6",
  "ResponsibleType": "36",
  "SuplrQltyInProcmtCertfnValidTo": "2023-01-10",
  "SuplrQltyInProcmtIsActive": true,
  "SuplrQltyMgmtSystemValidTo": "2010-06-20",
  "SupplierCorporateGroup": "p-24747136",
  "SupplierProcurementBlock": "36",
  "TaxNumber1": "Number1-24747136",
  "TaxNumber2": "r2-24747136",
  "TaxNumber3": "axNumber3-24747136",
  "TaxNumber4": "axNumber4-24747136",
  "TaxNumber5": "TaxNumber5-24747136",
  "TaxNumberResponsible": "TaxNumberResponsible-24747136",
  "TaxNumberType": "36",
  "SuplrProofOfDelivRlvtCode": "6",
  "BR_TaxIsSplit": true
}


### A_Supplier
# @name A_Supplier_PATCH
PATCH {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Supplier/r-24747136
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Supplier": "r-24747136",
  "AuthorizationGroup": "7136",
  "CreatedByUser": "ser-24747136",
  "CreationDate": "2010-04-10",
  "Customer": "r-24747136",
  "IsMarkedForDeletion": true,
  "IsNaturalPerson": "6",
  "PaymentIsBlockedForSupplier": true,
  "PostingIsBlocked": true,
  "PurchasingIsBlocked": true,
  "SupplierAccountGroup": "7136",
  "SupplierFullName": "SupplierFullName-24747136",
  "SupplierName": "SupplierName-24747136",
  "VATRegistration": "egistration-24747136",
  "BirthDate": "2007-06-24",
  "ConcatenatedInternationalLocNo": "LocNo-24747136",
  "DeletionIndicator": true,
  "FiscalAddress": "s-24747136",
  "Industry": "7136",
  "InternationalLocationNumber1": "4747136",
  "InternationalLocationNumber2": "47136",
  "IsNaturalPerson2": "6",
  "ResponsibleType": "36",
  "SuplrQltyInProcmtCertfnValidTo": "2023-01-10",
  "SuplrQltyInProcmtIsActive": true,
  "SuplrQltyMgmtSystemValidTo": "2010-06-20",
  "SupplierCorporateGroup": "p-24747136",
  "SupplierProcurementBlock": "36",
  "TaxNumber1": "Number1-24747136",
  "TaxNumber2": "r2-24747136",
  "TaxNumber3": "axNumber3-24747136",
  "TaxNumber4": "axNumber4-24747136",
  "TaxNumber5": "TaxNumber5-24747136",
  "TaxNumberResponsible": "TaxNumberResponsible-24747136",
  "TaxNumberType": "36",
  "SuplrProofOfDelivRlvtCode": "6",
  "BR_TaxIsSplit": true
}


### A_Supplier
# @name A_Supplier_DELETE
DELETE {{server}}/odata/v4/API_BUSINESS_PARTNER/A_Supplier/r-24747136
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
