@server=http://localhost:8080
@username=authenticated
@password=


### SalesDocHeaders
# @name SalesDocHeaders_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocHeaders
Authorization: Basic {{username}}:{{password}}


### SalesDocHeaders
# @name SalesDocHeaders_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocHeaders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "s-10606396",
  "SalesOrganization": "6396",
  "DistributionChannel": "96",
  "Division": "96",
  "SalesDocumentDate": "2016-07-09",
  "SalesDocumentType": "6396",
  "CustomerID": "D-10606396",
  "CustomerName": "CustomerName-10606396",
  "CustomerGroup": "6396",
  "Currency": "06396",
  "TotalNetAmount": 923690374480.41,
  "Status": "96",
  "ErrorMessage": "ErrorMessage-10606396",
  "items": [
    {
      "SalesDocumentItem": "877686",
      "MaterialCode": "erialCode-17877686",
      "MaterialName": "MaterialName-17877686",
      "MaterialGroup": "-17877686",
      "OrderQuantity": 3405882040.554,
      "OrderQuantityUnit": "686",
      "NetAmount": 7341141805409.07,
      "Currency": "77686",
      "Plant": "7686",
      "PlantName": "PlantName-17877686",
      "CompanyCode": "7686",
      "StorageLocation": "7686",
      "PricingDate": "2012-09-11",
      "details": [
        {
          "SalesDocument": "ls-9247650",
          "SalesDocumentItem": "247650",
          "SequentialNumber": "650",
          "DetailCategory": "50",
          "DetailText": "DetailText-9247650",
          "DetailAmount": 316851888614.12,
          "ConditionType": "7650",
          "ScheduleLineDate": "2021-06-23",
          "DeliveryScheduleQty": 5062555286.173,
          "Currency": "47650",
          "createdAt": "2004-11-13T00:00:00.000Z",
          "createdBy": "createdBy.5i7j6@example.net",
          "modifiedAt": "2001-09-20T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5i7j6@example.org"
        },
        {
          "SalesDocument": "ls-9247651",
          "SalesDocumentItem": "247651",
          "SequentialNumber": "651",
          "DetailCategory": "51",
          "DetailText": "DetailText-9247651",
          "DetailAmount": 7803694296990.32,
          "ConditionType": "7651",
          "ScheduleLineDate": "2005-12-24",
          "DeliveryScheduleQty": 7528839449.464,
          "Currency": "47651",
          "createdAt": "2020-01-10T00:00:00.000Z",
          "createdBy": "createdBy.5i7j7@example.com",
          "modifiedAt": "2011-10-16T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5i7j7@example.org"
        }
      ],
      "createdAt": "2007-02-03T00:00:00.000Z",
      "createdBy": "createdBy.an6ie@example.net",
      "modifiedAt": "2022-10-18T00:00:00.000Z",
      "modifiedBy": "modifiedBy.an6ie@example.com"
    },
    {
      "SalesDocumentItem": "877687",
      "MaterialCode": "erialCode-17877687",
      "MaterialName": "MaterialName-17877687",
      "MaterialGroup": "-17877687",
      "OrderQuantity": 7989345400.553,
      "OrderQuantityUnit": "687",
      "NetAmount": 397374750641.75,
      "Currency": "77687",
      "Plant": "7687",
      "PlantName": "PlantName-17877687",
      "CompanyCode": "7687",
      "StorageLocation": "7687",
      "PricingDate": "2017-11-17",
      "details": [
        {
          "SalesDocument": "ls-9601565",
          "SalesDocumentItem": "601565",
          "SequentialNumber": "565",
          "DetailCategory": "65",
          "DetailText": "DetailText-9601565",
          "DetailAmount": 7981712178147.75,
          "ConditionType": "1565",
          "ScheduleLineDate": "2010-01-24",
          "DeliveryScheduleQty": 3468793889.446,
          "Currency": "01565",
          "createdAt": "2017-11-16T00:00:00.000Z",
          "createdBy": "createdBy.5psm5@example.com",
          "modifiedAt": "2008-12-07T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5psm5@example.net"
        },
        {
          "SalesDocument": "ls-9601566",
          "SalesDocumentItem": "601566",
          "SequentialNumber": "566",
          "DetailCategory": "66",
          "DetailText": "DetailText-9601566",
          "DetailAmount": 7347008261566.25,
          "ConditionType": "1566",
          "ScheduleLineDate": "2015-12-02",
          "DeliveryScheduleQty": 4169960496.579,
          "Currency": "01566",
          "createdAt": "2013-06-10T00:00:00.000Z",
          "createdBy": "createdBy.5psm6@example.com",
          "modifiedAt": "2022-04-02T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5psm6@example.net"
        }
      ],
      "createdAt": "2011-01-13T00:00:00.000Z",
      "createdBy": "createdBy.an6if@example.net",
      "modifiedAt": "2006-04-27T00:00:00.000Z",
      "modifiedBy": "modifiedBy.an6if@example.com"
    }
  ],
  "createdAt": "2000-10-12T00:00:00.000Z",
  "createdBy": "createdBy.6bby4@example.net",
  "modifiedAt": "2009-01-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.6bby4@example.org"
}


### SalesDocHeaders
# @name SalesDocHeaders_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocHeaders/s-10606396
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "s-10606396",
  "SalesOrganization": "6396",
  "DistributionChannel": "96",
  "Division": "96",
  "SalesDocumentDate": "2016-07-09",
  "SalesDocumentType": "6396",
  "CustomerID": "D-10606396",
  "CustomerName": "CustomerName-10606396",
  "CustomerGroup": "6396",
  "Currency": "06396",
  "TotalNetAmount": 923690374480.41,
  "Status": "96",
  "ErrorMessage": "ErrorMessage-10606396",
  "items": [
    {
      "SalesDocumentItem": "877686",
      "MaterialCode": "erialCode-17877686",
      "MaterialName": "MaterialName-17877686",
      "MaterialGroup": "-17877686",
      "OrderQuantity": 3405882040.554,
      "OrderQuantityUnit": "686",
      "NetAmount": 7341141805409.07,
      "Currency": "77686",
      "Plant": "7686",
      "PlantName": "PlantName-17877686",
      "CompanyCode": "7686",
      "StorageLocation": "7686",
      "PricingDate": "2012-09-11",
      "details": [
        {
          "SalesDocument": "ls-9247650",
          "SalesDocumentItem": "247650",
          "SequentialNumber": "650",
          "DetailCategory": "50",
          "DetailText": "DetailText-9247650",
          "DetailAmount": 316851888614.12,
          "ConditionType": "7650",
          "ScheduleLineDate": "2021-06-23",
          "DeliveryScheduleQty": 5062555286.173,
          "Currency": "47650",
          "createdAt": "2004-11-13T00:00:00.000Z",
          "createdBy": "createdBy.5i7j6@example.net",
          "modifiedAt": "2001-09-20T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5i7j6@example.org"
        },
        {
          "SalesDocument": "ls-9247651",
          "SalesDocumentItem": "247651",
          "SequentialNumber": "651",
          "DetailCategory": "51",
          "DetailText": "DetailText-9247651",
          "DetailAmount": 7803694296990.32,
          "ConditionType": "7651",
          "ScheduleLineDate": "2005-12-24",
          "DeliveryScheduleQty": 7528839449.464,
          "Currency": "47651",
          "createdAt": "2020-01-10T00:00:00.000Z",
          "createdBy": "createdBy.5i7j7@example.com",
          "modifiedAt": "2011-10-16T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5i7j7@example.org"
        }
      ],
      "createdAt": "2007-02-03T00:00:00.000Z",
      "createdBy": "createdBy.an6ie@example.net",
      "modifiedAt": "2022-10-18T00:00:00.000Z",
      "modifiedBy": "modifiedBy.an6ie@example.com"
    },
    {
      "SalesDocumentItem": "877687",
      "MaterialCode": "erialCode-17877687",
      "MaterialName": "MaterialName-17877687",
      "MaterialGroup": "-17877687",
      "OrderQuantity": 7989345400.553,
      "OrderQuantityUnit": "687",
      "NetAmount": 397374750641.75,
      "Currency": "77687",
      "Plant": "7687",
      "PlantName": "PlantName-17877687",
      "CompanyCode": "7687",
      "StorageLocation": "7687",
      "PricingDate": "2017-11-17",
      "details": [
        {
          "SalesDocument": "ls-9601565",
          "SalesDocumentItem": "601565",
          "SequentialNumber": "565",
          "DetailCategory": "65",
          "DetailText": "DetailText-9601565",
          "DetailAmount": 7981712178147.75,
          "ConditionType": "1565",
          "ScheduleLineDate": "2010-01-24",
          "DeliveryScheduleQty": 3468793889.446,
          "Currency": "01565",
          "createdAt": "2017-11-16T00:00:00.000Z",
          "createdBy": "createdBy.5psm5@example.com",
          "modifiedAt": "2008-12-07T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5psm5@example.net"
        },
        {
          "SalesDocument": "ls-9601566",
          "SalesDocumentItem": "601566",
          "SequentialNumber": "566",
          "DetailCategory": "66",
          "DetailText": "DetailText-9601566",
          "DetailAmount": 7347008261566.25,
          "ConditionType": "1566",
          "ScheduleLineDate": "2015-12-02",
          "DeliveryScheduleQty": 4169960496.579,
          "Currency": "01566",
          "createdAt": "2013-06-10T00:00:00.000Z",
          "createdBy": "createdBy.5psm6@example.com",
          "modifiedAt": "2022-04-02T00:00:00.000Z",
          "modifiedBy": "modifiedBy.5psm6@example.net"
        }
      ],
      "createdAt": "2011-01-13T00:00:00.000Z",
      "createdBy": "createdBy.an6if@example.net",
      "modifiedAt": "2006-04-27T00:00:00.000Z",
      "modifiedBy": "modifiedBy.an6if@example.com"
    }
  ],
  "createdAt": "2000-10-12T00:00:00.000Z",
  "createdBy": "createdBy.6bby4@example.net",
  "modifiedAt": "2009-01-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.6bby4@example.org"
}


### SalesDocHeaders
# @name SalesDocHeaders_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocHeaders/s-10606396
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocItems
# @name SalesDocItems_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocItems
Authorization: Basic {{username}}:{{password}}


### SalesDocItems
# @name SalesDocItems_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocumentItem": "877686",
  "MaterialCode": "erialCode-17877686",
  "MaterialName": "MaterialName-17877686",
  "MaterialGroup": "-17877686",
  "OrderQuantity": 3405882040.554,
  "OrderQuantityUnit": "686",
  "NetAmount": 7341141805409.07,
  "Currency": "77686",
  "Plant": "7686",
  "PlantName": "PlantName-17877686",
  "CompanyCode": "7686",
  "StorageLocation": "7686",
  "PricingDate": "2012-09-11",
  "details": [
    {
      "SalesDocument": "ls-9247650",
      "SalesDocumentItem": "247650",
      "SequentialNumber": "650",
      "DetailCategory": "50",
      "DetailText": "DetailText-9247650",
      "DetailAmount": 316851888614.12,
      "ConditionType": "7650",
      "ScheduleLineDate": "2021-06-23",
      "DeliveryScheduleQty": 5062555286.173,
      "Currency": "47650",
      "createdAt": "2004-11-13T00:00:00.000Z",
      "createdBy": "createdBy.5i7j6@example.net",
      "modifiedAt": "2001-09-20T00:00:00.000Z",
      "modifiedBy": "modifiedBy.5i7j6@example.org"
    },
    {
      "SalesDocument": "ls-9247651",
      "SalesDocumentItem": "247651",
      "SequentialNumber": "651",
      "DetailCategory": "51",
      "DetailText": "DetailText-9247651",
      "DetailAmount": 7803694296990.32,
      "ConditionType": "7651",
      "ScheduleLineDate": "2005-12-24",
      "DeliveryScheduleQty": 7528839449.464,
      "Currency": "47651",
      "createdAt": "2020-01-10T00:00:00.000Z",
      "createdBy": "createdBy.5i7j7@example.com",
      "modifiedAt": "2011-10-16T00:00:00.000Z",
      "modifiedBy": "modifiedBy.5i7j7@example.org"
    }
  ],
  "createdAt": "2007-02-03T00:00:00.000Z",
  "createdBy": "createdBy.an6ie@example.net",
  "modifiedAt": "2022-10-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.an6ie@example.com"
}


### SalesDocItems
# @name SalesDocItems_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocItems(SalesDocument='s-10606396',SalesDocumentItem='877686')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocumentItem": "877686",
  "MaterialCode": "erialCode-17877686",
  "MaterialName": "MaterialName-17877686",
  "MaterialGroup": "-17877686",
  "OrderQuantity": 3405882040.554,
  "OrderQuantityUnit": "686",
  "NetAmount": 7341141805409.07,
  "Currency": "77686",
  "Plant": "7686",
  "PlantName": "PlantName-17877686",
  "CompanyCode": "7686",
  "StorageLocation": "7686",
  "PricingDate": "2012-09-11",
  "details": [
    {
      "SalesDocument": "ls-9247650",
      "SalesDocumentItem": "247650",
      "SequentialNumber": "650",
      "DetailCategory": "50",
      "DetailText": "DetailText-9247650",
      "DetailAmount": 316851888614.12,
      "ConditionType": "7650",
      "ScheduleLineDate": "2021-06-23",
      "DeliveryScheduleQty": 5062555286.173,
      "Currency": "47650",
      "createdAt": "2004-11-13T00:00:00.000Z",
      "createdBy": "createdBy.5i7j6@example.net",
      "modifiedAt": "2001-09-20T00:00:00.000Z",
      "modifiedBy": "modifiedBy.5i7j6@example.org"
    },
    {
      "SalesDocument": "ls-9247651",
      "SalesDocumentItem": "247651",
      "SequentialNumber": "651",
      "DetailCategory": "51",
      "DetailText": "DetailText-9247651",
      "DetailAmount": 7803694296990.32,
      "ConditionType": "7651",
      "ScheduleLineDate": "2005-12-24",
      "DeliveryScheduleQty": 7528839449.464,
      "Currency": "47651",
      "createdAt": "2020-01-10T00:00:00.000Z",
      "createdBy": "createdBy.5i7j7@example.com",
      "modifiedAt": "2011-10-16T00:00:00.000Z",
      "modifiedBy": "modifiedBy.5i7j7@example.org"
    }
  ],
  "createdAt": "2007-02-03T00:00:00.000Z",
  "createdBy": "createdBy.an6ie@example.net",
  "modifiedAt": "2022-10-18T00:00:00.000Z",
  "modifiedBy": "modifiedBy.an6ie@example.com"
}


### SalesDocItems
# @name SalesDocItems_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocItems(SalesDocument='s-10606396',SalesDocumentItem='877686')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocDetails
# @name SalesDocDetails_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocDetails
Authorization: Basic {{username}}:{{password}}


### SalesDocDetails
# @name SalesDocDetails_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocDetails
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "ls-9247650",
  "SalesDocumentItem": "247650",
  "SequentialNumber": "650",
  "DetailCategory": "50",
  "DetailText": "DetailText-9247650",
  "DetailAmount": 316851888614.12,
  "ConditionType": "7650",
  "ScheduleLineDate": "2021-06-23",
  "DeliveryScheduleQty": 5062555286.173,
  "Currency": "47650",
  "createdAt": "2004-11-13T00:00:00.000Z",
  "createdBy": "createdBy.5i7j6@example.net",
  "modifiedAt": "2001-09-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.5i7j6@example.org"
}


### SalesDocDetails
# @name SalesDocDetails_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocDetails(SalesDocument='ls-9247650',SalesDocumentItem='247650',SequentialNumber='650')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "ls-9247650",
  "SalesDocumentItem": "247650",
  "SequentialNumber": "650",
  "DetailCategory": "50",
  "DetailText": "DetailText-9247650",
  "DetailAmount": 316851888614.12,
  "ConditionType": "7650",
  "ScheduleLineDate": "2021-06-23",
  "DeliveryScheduleQty": 5062555286.173,
  "Currency": "47650",
  "createdAt": "2004-11-13T00:00:00.000Z",
  "createdBy": "createdBy.5i7j6@example.net",
  "modifiedAt": "2001-09-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.5i7j6@example.org"
}


### SalesDocDetails
# @name SalesDocDetails_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocDetails(SalesDocument='ls-9247650',SalesDocumentItem='247650',SequentialNumber='650')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocItemView
# @name SalesDocItemView_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocItemView
Authorization: Basic {{username}}:{{password}}


### S4SalesDocuments
# @name S4SalesDocuments_GET
GET {{server}}/odata/v4/api/sales-documents/S4SalesDocuments
Authorization: Basic {{username}}:{{password}}


### createSalesDocuments
# @name createSalesDocuments_POST
POST {{server}}/odata/v4/api/sales-documents/createSalesDocuments
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "salesDocument": "12345",
  "forceUpdate": false
}
