@server=http://localhost:8080
@username=authenticated
@password=


### SalesDocHeaders
# @name SalesDocHeaders_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocHeaders
Authorization: Basic {{username}}:{{password}}


### SalesDocHeaders
# @name SalesDocHeaders_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocHeaders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "rs-8013856",
  "SalesOrganization": "3856",
  "DistributionChannel": "56",
  "Division": "56",
  "SalesDocumentDate": "2021-04-22",
  "SalesDocumentType": "3856",
  "CustomerID": "ID-8013856",
  "CustomerName": "CustomerName-8013856",
  "CustomerGroup": "3856",
  "Currency": "13856",
  "TotalNetAmount": 2371466672574.77,
  "Status": "56",
  "ErrorMessage": "ErrorMessage-8013856",
  "items": [
    {
      "SalesDocumentItem": "868617",
      "MaterialCode": "erialCode-19868617",
      "MaterialName": "MaterialName-19868617",
      "MaterialGroup": "-19868617",
      "OrderQuantity": 5306456481.929,
      "OrderQuantityUnit": "617",
      "NetAmount": 4667637769038.55,
      "Currency": "68617",
      "Plant": "8617",
      "PlantName": "PlantName-19868617",
      "CompanyCode": "8617",
      "StorageLocation": "8617",
      "PricingDate": "2007-09-12",
      "details": [
        {
          "SalesDocument": "s-21622192",
          "SalesDocumentItem": "622192",
          "SequentialNumber": "192",
          "DetailCategory": "92",
          "DetailText": "DetailText-21622192",
          "DetailAmount": 603439963252.49,
          "ConditionType": "2192",
          "ScheduleLineDate": "2017-02-19",
          "DeliveryScheduleQty": 2416885209.269,
          "Currency": "22192",
          "createdAt": "2004-03-13T00:00:00.000Z",
          "createdBy": "createdBy.cvfsg@example.com",
          "modifiedAt": "2006-03-02T00:00:00.000Z",
          "modifiedBy": "modifiedBy.cvfsg@example.net"
        },
        {
          "SalesDocument": "s-21622193",
          "SalesDocumentItem": "622193",
          "SequentialNumber": "193",
          "DetailCategory": "93",
          "DetailText": "DetailText-21622193",
          "DetailAmount": 6701019260959.09,
          "ConditionType": "2193",
          "ScheduleLineDate": "2006-09-06",
          "DeliveryScheduleQty": 1948798592.705,
          "Currency": "22193",
          "createdAt": "2008-04-01T00:00:00.000Z",
          "createdBy": "createdBy.cvfsh@example.com",
          "modifiedAt": "2017-03-26T00:00:00.000Z",
          "modifiedBy": "modifiedBy.cvfsh@example.net"
        }
      ],
      "createdAt": "2012-07-10T00:00:00.000Z",
      "createdBy": "createdBy.btuq1@example.net",
      "modifiedAt": "2001-05-04T00:00:00.000Z",
      "modifiedBy": "modifiedBy.btuq1@example.org"
    },
    {
      "SalesDocumentItem": "868618",
      "MaterialCode": "erialCode-19868618",
      "MaterialName": "MaterialName-19868618",
      "MaterialGroup": "-19868618",
      "OrderQuantity": 7317207067.467,
      "OrderQuantityUnit": "618",
      "NetAmount": 3558638063226.08,
      "Currency": "68618",
      "Plant": "8618",
      "PlantName": "PlantName-19868618",
      "CompanyCode": "8618",
      "StorageLocation": "8618",
      "PricingDate": "2003-08-07",
      "details": [
        {
          "SalesDocument": "s-10541510",
          "SalesDocumentItem": "541510",
          "SequentialNumber": "510",
          "DetailCategory": "10",
          "DetailText": "DetailText-10541510",
          "DetailAmount": 8858342817558.02,
          "ConditionType": "1510",
          "ScheduleLineDate": "2002-05-18",
          "DeliveryScheduleQty": 3493390457.789,
          "Currency": "41510",
          "createdAt": "2003-02-26T00:00:00.000Z",
          "createdBy": "createdBy.69xvq@example.org",
          "modifiedAt": "2003-08-29T00:00:00.000Z",
          "modifiedBy": "modifiedBy.69xvq@example.com"
        },
        {
          "SalesDocument": "s-10541511",
          "SalesDocumentItem": "541511",
          "SequentialNumber": "511",
          "DetailCategory": "11",
          "DetailText": "DetailText-10541511",
          "DetailAmount": 6908804977609.06,
          "ConditionType": "1511",
          "ScheduleLineDate": "2004-03-24",
          "DeliveryScheduleQty": 8108359150.256,
          "Currency": "41511",
          "createdAt": "2017-07-07T00:00:00.000Z",
          "createdBy": "createdBy.69xvr@example.com",
          "modifiedAt": "2007-06-20T00:00:00.000Z",
          "modifiedBy": "modifiedBy.69xvr@example.org"
        }
      ],
      "createdAt": "2018-01-25T00:00:00.000Z",
      "createdBy": "createdBy.btuq2@example.com",
      "modifiedAt": "2013-02-05T00:00:00.000Z",
      "modifiedBy": "modifiedBy.btuq2@example.com"
    }
  ],
  "createdAt": "2011-03-16T00:00:00.000Z",
  "createdBy": "createdBy.4rrj4@example.org",
  "modifiedAt": "2002-12-17T00:00:00.000Z",
  "modifiedBy": "modifiedBy.4rrj4@example.com"
}


### SalesDocHeaders
# @name SalesDocHeaders_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocHeaders/rs-8013856
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "rs-8013856",
  "SalesOrganization": "3856",
  "DistributionChannel": "56",
  "Division": "56",
  "SalesDocumentDate": "2021-04-22",
  "SalesDocumentType": "3856",
  "CustomerID": "ID-8013856",
  "CustomerName": "CustomerName-8013856",
  "CustomerGroup": "3856",
  "Currency": "13856",
  "TotalNetAmount": 2371466672574.77,
  "Status": "56",
  "ErrorMessage": "ErrorMessage-8013856",
  "items": [
    {
      "SalesDocumentItem": "868617",
      "MaterialCode": "erialCode-19868617",
      "MaterialName": "MaterialName-19868617",
      "MaterialGroup": "-19868617",
      "OrderQuantity": 5306456481.929,
      "OrderQuantityUnit": "617",
      "NetAmount": 4667637769038.55,
      "Currency": "68617",
      "Plant": "8617",
      "PlantName": "PlantName-19868617",
      "CompanyCode": "8617",
      "StorageLocation": "8617",
      "PricingDate": "2007-09-12",
      "details": [
        {
          "SalesDocument": "s-21622192",
          "SalesDocumentItem": "622192",
          "SequentialNumber": "192",
          "DetailCategory": "92",
          "DetailText": "DetailText-21622192",
          "DetailAmount": 603439963252.49,
          "ConditionType": "2192",
          "ScheduleLineDate": "2017-02-19",
          "DeliveryScheduleQty": 2416885209.269,
          "Currency": "22192",
          "createdAt": "2004-03-13T00:00:00.000Z",
          "createdBy": "createdBy.cvfsg@example.com",
          "modifiedAt": "2006-03-02T00:00:00.000Z",
          "modifiedBy": "modifiedBy.cvfsg@example.net"
        },
        {
          "SalesDocument": "s-21622193",
          "SalesDocumentItem": "622193",
          "SequentialNumber": "193",
          "DetailCategory": "93",
          "DetailText": "DetailText-21622193",
          "DetailAmount": 6701019260959.09,
          "ConditionType": "2193",
          "ScheduleLineDate": "2006-09-06",
          "DeliveryScheduleQty": 1948798592.705,
          "Currency": "22193",
          "createdAt": "2008-04-01T00:00:00.000Z",
          "createdBy": "createdBy.cvfsh@example.com",
          "modifiedAt": "2017-03-26T00:00:00.000Z",
          "modifiedBy": "modifiedBy.cvfsh@example.net"
        }
      ],
      "createdAt": "2012-07-10T00:00:00.000Z",
      "createdBy": "createdBy.btuq1@example.net",
      "modifiedAt": "2001-05-04T00:00:00.000Z",
      "modifiedBy": "modifiedBy.btuq1@example.org"
    },
    {
      "SalesDocumentItem": "868618",
      "MaterialCode": "erialCode-19868618",
      "MaterialName": "MaterialName-19868618",
      "MaterialGroup": "-19868618",
      "OrderQuantity": 7317207067.467,
      "OrderQuantityUnit": "618",
      "NetAmount": 3558638063226.08,
      "Currency": "68618",
      "Plant": "8618",
      "PlantName": "PlantName-19868618",
      "CompanyCode": "8618",
      "StorageLocation": "8618",
      "PricingDate": "2003-08-07",
      "details": [
        {
          "SalesDocument": "s-10541510",
          "SalesDocumentItem": "541510",
          "SequentialNumber": "510",
          "DetailCategory": "10",
          "DetailText": "DetailText-10541510",
          "DetailAmount": 8858342817558.02,
          "ConditionType": "1510",
          "ScheduleLineDate": "2002-05-18",
          "DeliveryScheduleQty": 3493390457.789,
          "Currency": "41510",
          "createdAt": "2003-02-26T00:00:00.000Z",
          "createdBy": "createdBy.69xvq@example.org",
          "modifiedAt": "2003-08-29T00:00:00.000Z",
          "modifiedBy": "modifiedBy.69xvq@example.com"
        },
        {
          "SalesDocument": "s-10541511",
          "SalesDocumentItem": "541511",
          "SequentialNumber": "511",
          "DetailCategory": "11",
          "DetailText": "DetailText-10541511",
          "DetailAmount": 6908804977609.06,
          "ConditionType": "1511",
          "ScheduleLineDate": "2004-03-24",
          "DeliveryScheduleQty": 8108359150.256,
          "Currency": "41511",
          "createdAt": "2017-07-07T00:00:00.000Z",
          "createdBy": "createdBy.69xvr@example.com",
          "modifiedAt": "2007-06-20T00:00:00.000Z",
          "modifiedBy": "modifiedBy.69xvr@example.org"
        }
      ],
      "createdAt": "2018-01-25T00:00:00.000Z",
      "createdBy": "createdBy.btuq2@example.com",
      "modifiedAt": "2013-02-05T00:00:00.000Z",
      "modifiedBy": "modifiedBy.btuq2@example.com"
    }
  ],
  "createdAt": "2011-03-16T00:00:00.000Z",
  "createdBy": "createdBy.4rrj4@example.org",
  "modifiedAt": "2002-12-17T00:00:00.000Z",
  "modifiedBy": "modifiedBy.4rrj4@example.com"
}


### SalesDocHeaders
# @name SalesDocHeaders_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocHeaders/rs-8013856
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocItems
# @name SalesDocItems_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocItems
Authorization: Basic {{username}}:{{password}}


### SalesDocItems
# @name SalesDocItems_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocumentItem": "868617",
  "MaterialCode": "erialCode-19868617",
  "MaterialName": "MaterialName-19868617",
  "MaterialGroup": "-19868617",
  "OrderQuantity": 5306456481.929,
  "OrderQuantityUnit": "617",
  "NetAmount": 4667637769038.55,
  "Currency": "68617",
  "Plant": "8617",
  "PlantName": "PlantName-19868617",
  "CompanyCode": "8617",
  "StorageLocation": "8617",
  "PricingDate": "2007-09-12",
  "details": [
    {
      "SalesDocument": "s-21622192",
      "SalesDocumentItem": "622192",
      "SequentialNumber": "192",
      "DetailCategory": "92",
      "DetailText": "DetailText-21622192",
      "DetailAmount": 603439963252.49,
      "ConditionType": "2192",
      "ScheduleLineDate": "2017-02-19",
      "DeliveryScheduleQty": 2416885209.269,
      "Currency": "22192",
      "createdAt": "2004-03-13T00:00:00.000Z",
      "createdBy": "createdBy.cvfsg@example.com",
      "modifiedAt": "2006-03-02T00:00:00.000Z",
      "modifiedBy": "modifiedBy.cvfsg@example.net"
    },
    {
      "SalesDocument": "s-21622193",
      "SalesDocumentItem": "622193",
      "SequentialNumber": "193",
      "DetailCategory": "93",
      "DetailText": "DetailText-21622193",
      "DetailAmount": 6701019260959.09,
      "ConditionType": "2193",
      "ScheduleLineDate": "2006-09-06",
      "DeliveryScheduleQty": 1948798592.705,
      "Currency": "22193",
      "createdAt": "2008-04-01T00:00:00.000Z",
      "createdBy": "createdBy.cvfsh@example.com",
      "modifiedAt": "2017-03-26T00:00:00.000Z",
      "modifiedBy": "modifiedBy.cvfsh@example.net"
    }
  ],
  "createdAt": "2012-07-10T00:00:00.000Z",
  "createdBy": "createdBy.btuq1@example.net",
  "modifiedAt": "2001-05-04T00:00:00.000Z",
  "modifiedBy": "modifiedBy.btuq1@example.org"
}


### SalesDocItems
# @name SalesDocItems_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocItems(SalesDocument='rs-8013856',SalesDocumentItem='868617')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocumentItem": "868617",
  "MaterialCode": "erialCode-19868617",
  "MaterialName": "MaterialName-19868617",
  "MaterialGroup": "-19868617",
  "OrderQuantity": 5306456481.929,
  "OrderQuantityUnit": "617",
  "NetAmount": 4667637769038.55,
  "Currency": "68617",
  "Plant": "8617",
  "PlantName": "PlantName-19868617",
  "CompanyCode": "8617",
  "StorageLocation": "8617",
  "PricingDate": "2007-09-12",
  "details": [
    {
      "SalesDocument": "s-21622192",
      "SalesDocumentItem": "622192",
      "SequentialNumber": "192",
      "DetailCategory": "92",
      "DetailText": "DetailText-21622192",
      "DetailAmount": 603439963252.49,
      "ConditionType": "2192",
      "ScheduleLineDate": "2017-02-19",
      "DeliveryScheduleQty": 2416885209.269,
      "Currency": "22192",
      "createdAt": "2004-03-13T00:00:00.000Z",
      "createdBy": "createdBy.cvfsg@example.com",
      "modifiedAt": "2006-03-02T00:00:00.000Z",
      "modifiedBy": "modifiedBy.cvfsg@example.net"
    },
    {
      "SalesDocument": "s-21622193",
      "SalesDocumentItem": "622193",
      "SequentialNumber": "193",
      "DetailCategory": "93",
      "DetailText": "DetailText-21622193",
      "DetailAmount": 6701019260959.09,
      "ConditionType": "2193",
      "ScheduleLineDate": "2006-09-06",
      "DeliveryScheduleQty": 1948798592.705,
      "Currency": "22193",
      "createdAt": "2008-04-01T00:00:00.000Z",
      "createdBy": "createdBy.cvfsh@example.com",
      "modifiedAt": "2017-03-26T00:00:00.000Z",
      "modifiedBy": "modifiedBy.cvfsh@example.net"
    }
  ],
  "createdAt": "2012-07-10T00:00:00.000Z",
  "createdBy": "createdBy.btuq1@example.net",
  "modifiedAt": "2001-05-04T00:00:00.000Z",
  "modifiedBy": "modifiedBy.btuq1@example.org"
}


### SalesDocItems
# @name SalesDocItems_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocItems(SalesDocument='rs-8013856',SalesDocumentItem='868617')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocDetails
# @name SalesDocDetails_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocDetails
Authorization: Basic {{username}}:{{password}}


### SalesDocDetails
# @name SalesDocDetails_POST
POST {{server}}/odata/v4/api/sales-documents/SalesDocDetails
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "s-21622192",
  "SalesDocumentItem": "622192",
  "SequentialNumber": "192",
  "DetailCategory": "92",
  "DetailText": "DetailText-21622192",
  "DetailAmount": 603439963252.49,
  "ConditionType": "2192",
  "ScheduleLineDate": "2017-02-19",
  "DeliveryScheduleQty": 2416885209.269,
  "Currency": "22192",
  "createdAt": "2004-03-13T00:00:00.000Z",
  "createdBy": "createdBy.cvfsg@example.com",
  "modifiedAt": "2006-03-02T00:00:00.000Z",
  "modifiedBy": "modifiedBy.cvfsg@example.net"
}


### SalesDocDetails
# @name SalesDocDetails_PATCH
PATCH {{server}}/odata/v4/api/sales-documents/SalesDocDetails(SalesDocument='s-21622192',SalesDocumentItem='622192',SequentialNumber='192')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "s-21622192",
  "SalesDocumentItem": "622192",
  "SequentialNumber": "192",
  "DetailCategory": "92",
  "DetailText": "DetailText-21622192",
  "DetailAmount": 603439963252.49,
  "ConditionType": "2192",
  "ScheduleLineDate": "2017-02-19",
  "DeliveryScheduleQty": 2416885209.269,
  "Currency": "22192",
  "createdAt": "2004-03-13T00:00:00.000Z",
  "createdBy": "createdBy.cvfsg@example.com",
  "modifiedAt": "2006-03-02T00:00:00.000Z",
  "modifiedBy": "modifiedBy.cvfsg@example.net"
}


### SalesDocDetails
# @name SalesDocDetails_DELETE
DELETE {{server}}/odata/v4/api/sales-documents/SalesDocDetails(SalesDocument='s-21622192',SalesDocumentItem='622192',SequentialNumber='192')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### SalesDocItemView
# @name SalesDocItemView_GET
GET {{server}}/odata/v4/api/sales-documents/SalesDocItemView
Authorization: Basic {{username}}:{{password}}


### S4SalesDocuments
# @name S4SalesDocuments_GET
GET {{server}}/odata/v4/api/sales-documents/S4SalesDocuments
Authorization: Basic {{username}}:{{password}}


### createSalesDocuments
# @name createSalesDocuments_POST
POST {{server}}/odata/v4/api/sales-documents/createSalesDocuments
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "salesDocument": "nt-7538443",
  "forceUpdate": false
}


### updateS4Status
# @name updateS4Status_POST
POST {{server}}/odata/v4/api/sales-documents/updateS4Status
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}
