@server=http://localhost:8080
@username=authenticated
@password=


### ZcSalesDocument
# @name ZcSalesDocument_GET
GET {{server}}/odata/v4/ZC_SALESDOCUMENT_SERVICE/ZcSalesDocument
Authorization: Basic {{username}}:{{password}}


### ZcSalesDocument
# @name ZcSalesDocument_POST
POST {{server}}/odata/v4/ZC_SALESDOCUMENT_SERVICE/ZcSalesDocument
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "t-18191479",
  "SalesDocumentItem": "191479",
  "SequentialNumber": "479",
  "SalesOrganization": "1479",
  "DistributionChannel": "79",
  "Division": "79",
  "SalesDocumentDate": "2002-12-27",
  "SalesDocumentType": "1479",
  "CustomerID": "D-18191479",
  "MaterialCode": "erialCode-18191479",
  "OrderQuantity": 4822140416.661,
  "OrderQuantityUnit": "479",
  "NetAmount": 656616661377.92,
  "Currency": "91479",
  "Plant": "1479",
  "StorageLocation": "1479",
  "PricingDate": "2008-10-23",
  "DetailCategory": "79",
  "DetailText": "DetailText-18191479",
  "DetailAmount": 8484471341696.23,
  "ConditionType": "1479",
  "ScheduleLineDate": "2012-05-18",
  "DeliveryScheduleQty": 754948486.982
}


### ZcSalesDocument
# @name ZcSalesDocument_PATCH
PATCH {{server}}/odata/v4/ZC_SALESDOCUMENT_SERVICE/ZcSalesDocument(SalesDocument='t-18191479',SalesDocumentItem='191479',SequentialNumber='479')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SalesDocument": "t-18191479",
  "SalesDocumentItem": "191479",
  "SequentialNumber": "479",
  "SalesOrganization": "1479",
  "DistributionChannel": "79",
  "Division": "79",
  "SalesDocumentDate": "2002-12-27",
  "SalesDocumentType": "1479",
  "CustomerID": "D-18191479",
  "MaterialCode": "erialCode-18191479",
  "OrderQuantity": 4822140416.661,
  "OrderQuantityUnit": "479",
  "NetAmount": 656616661377.92,
  "Currency": "91479",
  "Plant": "1479",
  "StorageLocation": "1479",
  "PricingDate": "2008-10-23",
  "DetailCategory": "79",
  "DetailText": "DetailText-18191479",
  "DetailAmount": 8484471341696.23,
  "ConditionType": "1479",
  "ScheduleLineDate": "2012-05-18",
  "DeliveryScheduleQty": 754948486.982
}


### ZcSalesDocument
# @name ZcSalesDocument_DELETE
DELETE {{server}}/odata/v4/ZC_SALESDOCUMENT_SERVICE/ZcSalesDocument(SalesDocument='t-18191479',SalesDocumentItem='191479',SequentialNumber='479')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
