@server=http://localhost:8080
@username=authenticated
@password=


### UpdateSalesDocStatus
# @name UpdateSalesDocStatus_GET
GET {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/UpdateSalesDocStatus
Authorization: Basic {{username}}:{{password}}


### UpdateSalesDocStatus
# @name UpdateSalesDocStatus_POST
POST {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/UpdateSalesDocStatus
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "p_key": "7",
  "c_key": "7",
  "SalesDocument": "t-24590887",
  "SalesDocumentItem": "590887",
  "ProcessingStatus": "87",
  "ProcessedDate": "e-24590887",
  "ProcessedBy": "dBy-24590887",
  "Remark": "Remark-24590887",
  "InternalCode": "nternalCode-24590887"
}


### UpdateSalesDocStatus
# @name UpdateSalesDocStatus_PATCH
PATCH {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/UpdateSalesDocStatus(p_key='7',c_key='7')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "p_key": "7",
  "c_key": "7",
  "SalesDocument": "t-24590887",
  "SalesDocumentItem": "590887",
  "ProcessingStatus": "87",
  "ProcessedDate": "e-24590887",
  "ProcessedBy": "dBy-24590887",
  "Remark": "Remark-24590887",
  "InternalCode": "nternalCode-24590887"
}


### UpdateSalesDocStatus
# @name UpdateSalesDocStatus_DELETE
DELETE {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/UpdateSalesDocStatus(p_key='7',c_key='7')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### InsertSalesDocLog
# @name InsertSalesDocLog_GET
GET {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/InsertSalesDocLog
Authorization: Basic {{username}}:{{password}}


### InsertSalesDocLog
# @name InsertSalesDocLog_POST
POST {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/InsertSalesDocLog
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "p_key": "9",
  "c_key": "9",
  "SalesDocument": "nt-8599939",
  "SalesDocumentItem": "599939",
  "LogType": "9",
  "LogMessage": "LogMessage-8599939"
}


### InsertSalesDocLog
# @name InsertSalesDocLog_PATCH
PATCH {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/InsertSalesDocLog(p_key='9',c_key='9')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "p_key": "9",
  "c_key": "9",
  "SalesDocument": "nt-8599939",
  "SalesDocumentItem": "599939",
  "LogType": "9",
  "LogMessage": "LogMessage-8599939"
}


### InsertSalesDocLog
# @name InsertSalesDocLog_DELETE
DELETE {{server}}/odata/v4/ZS_SALESDOC_UPDATE_SRV/InsertSalesDocLog(p_key='9',c_key='9')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
