
---
spring:
  sql.init.platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  config:
    activate:
      on-profile: default,mocked,develop
cds:
  data-source.auto-config.enabled: false
  security:
    mock:
      enabled: true
  remote:
    services:
      '[ZS_SALESDOC_UPDATE_SRV]':
        destination:
          name: ZS_SALESDOC_UPDATE_SRV
        type: odata-v2
  
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
---


